import React from "react";
import Head from "next/head";

interface ISeoProps {
  city: ICity | null;
}

const SEO: React.FC<ISeoProps> = ({ city }) => (
  <Head>
    <title>{city ? `Weather in ${city.city}` : "Current weather"}</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);

export default SEO;
