import getMainPageInitialProps from "../src/initialProps/getMainPageInitialProps";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import withCommonProps from "utils/withCommonProps";
import WeatherCard from "components/WeatherCard";
import Footer from "components/Footer";

interface IHomeProps {
  weather: IWeather;
  weatherInImportantCities: IWeather[];
}

const Home: React.FC<IHomeProps> = ({ weather, weatherInImportantCities }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Current Weather</h1>
        <WeatherCard weather={weather} />
      </main>

      <Footer importantCityWeathers={weatherInImportantCities} />
    </div>
  );
};

export const getServerSideProps = withCommonProps(getMainPageInitialProps);

export default Home;
